In [22]:
import DataProcess
reload(DataProcess)
from DataProcess import load_mnist
import numpy as np

In [23]:
data  = load_mnist(dataset="training", path = '../')

/Library/Python/2.7/site-packages/scipy/stats/stats.py:2101: RuntimeWarning: invalid value encountered in true_divide
  return (a - mns) / sstd


In [28]:
data[1][0:49999]

array([4, 4, 7, ..., 7, 6, 4], dtype=int8)

In [194]:
import matplotlib.pyplot as plt

images = data[0]   
image = images[1]
image = image[1:].reshape(28,28)
plt.imshow(image, cmap=plt.get_cmap('gray'))
plt.show()

In [193]:
stats.zscore(b)
print b.shape
range(0)

(2, 3)


[]

In [35]:
b[1] = np.array([[1],[2],[3]]).reshape(1,3)

In [164]:
range(3)

[0, 1, 2]

In [161]:
a = np.array([1 ,3,3])
aaa = [1,2,3,4,5]

In [163]:
np.random.shuffle(aaa)
aaa

[2, 3, 4, 1, 5]

In [243]:
a = np.array([[1,2,3],[2,3,4],[4,5,6]])
a
b = np.array([3,5,7])

for ina, inb in zip(a,b) :
    print ina, inb
a[1:,:]

[1 2 3] 3
[2 3 4] 5
[4 5 6] 7


array([[2, 3, 4],
       [4, 5, 6]])

In [223]:
a[:,1] = 0
a[:,0] = 0
a

array([[0, 0, 3],
       [0, 0, 4],
       [0, 0, 6]])

In [166]:
np.random.shuffle(a)
a

array([3, 1, 3])

In [167]:
a

array([3, 1, 3])

In [14]:
a[0] = [3,4,5]

In [15]:
a

array([[3, 4, 5],
       [2, 3, 4],
       [4, 5, 6]])

In [16]:
a[0] = np.array([1,2,3])

In [17]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [30]:
b

array([ 0.,  0.,  0.])

In [24]:
b

0.33333333333333331

In [28]:
a[0] = b

In [168]:
a

array([3, 1, 3])

In [50]:
a

array([[0, 0, 0],
       [2, 3, 4],
       [4, 5, 6]])

In [51]:
a[0] = [1,3,2]

In [52]:
a

array([[1, 3, 2],
       [2, 3, 4],
       [4, 5, 6]])

In [53]:
meanA = a.mean(axis=0)

In [54]:
meanA

array([ 2.33333333,  3.66666667,  4.        ])

In [55]:
a - meanA

array([[-1.33333333, -0.66666667, -2.        ],
       [-0.33333333, -0.66666667,  0.        ],
       [ 1.66666667,  1.33333333,  2.        ]])

In [63]:
a

array([[1, 3, 2],
       [2, 3, 4],
       [4, 5, 6]])

In [64]:
from scipy import stats

In [65]:
stats.zscore(a)

array([[-1.06904497, -0.70710678, -1.22474487],
       [-0.26726124, -0.70710678,  0.        ],
       [ 1.33630621,  1.41421356,  1.22474487]])

In [69]:
a[:,0] = [1,1,1]
a

array([[1, 3, 2],
       [1, 3, 4],
       [1, 5, 6]])

In [70]:
stats.zscore(a)

array([[        nan, -0.70710678, -1.22474487],
       [        nan, -0.70710678,  0.        ],
       [        nan,  1.41421356,  1.22474487]])

In [78]:
a

array([[1, 3, 2],
       [1, 3, 4],
       [1, 5, 6]])

In [219]:
np.insert(a, 0, 1, axis = 1)

IndexError: axis 1 is out of bounds for an array of dimension 1

In [196]:
a = [[1,2],[3,4]]
a

[[1, 2], [3, 4]]

In [198]:
b = [3,4]
b

[3, 4]

In [201]:
np.dot(a,b)

array([11, 25])

In [202]:
np.range(10)

AttributeError: 'module' object has no attribute 'range'

In [203]:
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [204]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [206]:
1*(np.array(range(10)) == 1)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [210]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [211]:
a = np.array([1,2,3,4])

In [212]:
a

array([1, 2, 3, 4])

In [213]:
[1,a]

[1, array([1, 2, 3, 4])]

In [215]:
np.insert(a, 0, 1)

array([1, 1, 2, 3, 4])

In [216]:
a = np.insert(a, 0, 1)

In [217]:
a

array([1, 1, 2, 3, 4])

In [218]:
a[0:3]

array([1, 1, 2])

In [224]:
np.exp(3)

20.085536923187668

In [225]:
a = np.array([1,3,4])
a

array([1, 3, 4])

In [228]:
np.exp(a)/np.sum(np.exp(a))

array([ 0.03511903,  0.25949646,  0.70538451])

In [229]:
np.tanh(a)

array([ 0.76159416,  0.99505475,  0.9993293 ])

In [230]:
np.multiply(tanh(a),np.tanh(a))

array([ 0.58002566,  0.99013396,  0.99865905])

In [231]:
np.multiply(tanh(a),np.tanh(a))

array([ 0.58002566,  0.99013396,  0.99865905])

In [232]:
a

array([1, 3, 4])

In [244]:
a = np.array([])

In [245]:
a

array([], dtype=float64)

In [254]:
a = np.insert(a, 7)
np.insert(a, 0,2)

TypeError: insert() takes at least 3 arguments (2 given)

In [253]:
 np.power(10.0, -1)

0.10000000000000001

In [267]:
a = np.append(a, 100)

In [271]:
a[-3:] = [88, 88, 88]
a

array([ 1,  2,  3, 88, 88, 88])

In [257]:
import matplotlib.pyplot as plt

In [13]:
a = [1, 2, 3,4]
b = [2,4,6,8]

aa = [-1,-4, -5, -6]
bb = [-1,-5, -4, -3]

aaa = [3,4,5,8]
bbb = [4,5,6,7]

p1, = plt.plot(a,b)
p2, = plt.plot(aa,bb)
p3, = plt.plot(aaa,bbb)

plt.legend([p1,p2,p3],["line1", "line2", "line3"])
plt.show()


In [15]:
plt.plot(a,b)
plt.plot(aa,bb)
plt.plot(aaa,bbb)
plt.legend(["line1", "line2", "line3"])
plt.show()

In [21]:
import numpy as np
np.linspace(0,10,11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [5]:
import matplotlib.pyplot as plt
plt.plot(a,b,'ro-',linewidth = 5)
plt.savefig('./testsavefig.pdf')

In [30]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [80]:
import multilayerNN
import FunctionGradient
reload(multilayerNN)
reload(FunctionGradient)
from multilayerNN import HiddenLayer
from multilayerNN import MultiLayerPerceptron
from FunctionGradient import tanh, tanhGradient

In [81]:
rng = np.random.RandomState(1234)
hiddenLayer = HiddenLayer(rng,10,10,tanh,tanhGradient)
MultiLayerPerceptron(rng, 28*28 + 1, 50, 10, np.power(10.0, -5))

In [58]:
print tanhGradient([0,0,0,0])

None


In [68]:
a = [np.array([[1,3],[2,3],[4,4]])]
b = [np.array([[2,5,9],[3,4,5]])]

In [69]:
a + b

[array([[1, 3],
        [2, 3],
        [4, 4]]), array([[2, 5, 9],
        [3, 4, 5]])]

In [82]:
range(1,3,1)

[1, 2]

In [83]:
3 / 5

0

In [84]:
3.0 / 5

0.6

In [94]:
a = np.array([[1,3],[2,3],[4,4]])

In [86]:
aa = np.array([1,3,4])

In [97]:
for aele,aaele in zip(a,aa):
    print aele, aaele

[1 3] 1
[2 3] 3
[4 4] 4


In [98]:
a = [3,4,5]

In [99]:
a.append(7)

In [100]:
a

[3, 4, 5, 7]

In [101]:
np.max([1,2)

ValueError: 'axis' entry is out of bounds

In [103]:
np.amax([1,2])

2

In [104]:
a

[3, 4, 5, 7]

In [106]:
np.maximum(a,6)

array([6, 6, 6, 7])

In [111]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [112]:
np.ones(a.shape)

array([ 1.,  1.,  1.])

In [113]:
3 <= 2

False

In [114]:
10-5

5

In [117]:
10**(5)

100000

In [118]:
1.0 / (1 + np.exp(-np.array([1,3,4])))

array([ 0.73105858,  0.95257413,  0.98201379])

In [121]:
1/np.exp(10000000)

/Library/Python/2.7/site-packages/ipykernel/__main__.py:1: RuntimeWarning: overflow encountered in exp
  if __name__ == '__main__':


0.0

In [120]:
1/inf

NameError: name 'inf' is not defined

In [1]:
abs(-1)

1

In [2]:
abs(0.92 - 0.9) / 0.9 

0.02222222222222224

In [12]:
import numpy as np
np.exp(1000) / np.exp(1000)

/Library/Python/2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app
/Library/Python/2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in double_scalars
  from ipykernel import kernelapp as app


nan